"""unique user_id on applications

Revision ID: 2e848ea3b7e7
Revises: 66f0ec28389d
Create Date: 2026-04-24 10:32:14.618786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e848ea3b7e7'
down_revision: Union[str, Sequence[str], None] = '66f0ec28389d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_applications_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_applications_user_id', type_='unique')

    # ### end Alembic commands ###
