"""add_division_to_rubrics

Revision ID: 3990209e4c56
Revises: 2e848ea3b7e7
Create Date: 2026-04-25 00:03:08.148607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3990209e4c56'
down_revision: Union[str, Sequence[str], None] = '2e848ea3b7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_rubrics_division'), ['division'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubrics_division'))
        batch_op.drop_column('division')

    # ### end Alembic commands ###
