"""add_recruitment_periods_and_period_id_on_applications

Revision ID: 9ce1c5537331
Revises: 3990209e4c56
Create Date: 2026-04-25 13:42:04.948400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce1c5537331'
down_revision: Union[str, Sequence[str], None] = '3990209e4c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitment_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('threshold_n', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_applications_period_id'), ['period_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_applications_period_id',
            'recruitment_periods',
            ['period_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_applications_period_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_applications_period_id'))
        batch_op.drop_column('period_id')

    op.drop_table('recruitment_periods')
    # ### end Alembic commands ###
